import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>캐럿마켓</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">
          캐럿마켓에 오신 걸 환영합니다!
        </h1>
        <div className="font-bold underline">테스트</div>
        <Link href="/login">
          <a>로그인</a>
        </Link>
      </main>
    </div>
  );
};

export default Home;
