import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Button } from "@mui/material";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>캐럿마켓</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>캐럿마켓 로그인</h1>
        <Button variant="text">Text</Button>
        <Link href="/">
          <a>돌아가기</a>
        </Link>
      </main>
    </div>
  );
};

export default Home;
