import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Button } from "@mui/material";
import { useSession, signIn, signOut } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <div>
      <Head>
        <title>캐럿마켓</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="w-full flex flex-col items-center p-3">
        <h1 className="font-bold pt-2 pb-4 text-center text-xl">LOGIN</h1>
        {/*session && (
          <div className="pb-5">
            <div>{session?.user?.name ?? "사용자"}님 환영합니다!</div>
            <div>{session?.user?.email ?? "이메일이 없습니다."}</div>
            <div>{JSON.stringify(session)}</div>
          </div>
        )*/}
        <div>
          {session ? (
            <>
              <Button variant="outlined" onClick={() => signOut()}>
                로그아웃
              </Button>
            </>
          ) : (
            <>
              <Button variant="outlined" onClick={() => signIn()}>
                SNS 로그인
              </Button>
            </>
          )}
          <br />
          {/*<Link href="/">
            <a>돌아가기</a>
          </Link>*/}
        </div>
      </main>
    </div>
  );
};

export default Home;
